{% set name = "styro" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/styro-{{ version }}.tar.gz
  sha256: 04925ab50c09813f40ff89568740afc9aed1580d9e4921e2f9b840ff4f2bf14c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - GitPython >=3,<4
    - requests >=2,<3
    - typer-slim >=0.13,<0.16

test:
  imports:
    - styro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - git

about:
  home: https://github.com/gerlero/styro
  summary: A package manager for OpenFOAM
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
