{% set name = "styro" %}
{% set version = "0.1.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/styro-{{ version }}.tar.gz
  sha256: 4c37373cf14262b4e8997c12e5c5349373e30dfb0349e5009fa504e2f65e9541

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9,<0.10
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3,<4
    - cyclopts >=3.24,<5
    - typing-extensions >=4,<5

test:
  imports:
    - styro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - git

about:
  home: https://github.com/gerlero/styro
  summary: Package manager for OpenFOAM
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
