{% set name = "styro" %}
{% set version = "0.1.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/styro-{{ version }}.tar.gz
  sha256: 91eb7d61f05f95f76bc006227a3ed83e9ab0350c4ed3ade6ef696966b989d710

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.12,<0.13
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.6,<4
    - aioshutil >=1,<2
    - cyclopts >=3.24,<5
    - typing-extensions >=4.4,<5

test:
  imports:
    - styro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - git

about:
  home: https://github.com/gerlero/styro
  summary: Package manager for OpenFOAM
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
