{% set name = "styro" %}
{% set version = "0.1.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/styro-{{ version }}.tar.gz
  sha256: 42f7aba60b1342c3eeb037cdbe5acf6eb3ea9b022059441ae13cacc74a554421

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3,<4
    - cyclopts >=3.24,<4
    - typing-extensions >=4,<5

test:
  imports:
    - styro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - git

about:
  home: https://github.com/gerlero/styro
  summary: Package manager for OpenFOAM
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gerlero
